import json
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from web3 import Web3

# -----------------------------------------------
# Connect to local Ganache instance (URL from config.py)
# -----------------------------------------------
GANACHE_URL = config.GANACHE_URL
w3 = Web3(Web3.HTTPProvider(GANACHE_URL))


def get_web3():
    """Returns the Web3 instance if connected, else None."""
    if w3.is_connected():
        return w3
    return None


def get_deployed_contract_address():
    """
    Reads the deployed contract address from contract_address.txt.
    This file is generated by blockchain/deploy_contract.py.
    Returns None if not found.
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    address_file = os.path.join(base_dir, "contract_address.txt")

    if not os.path.exists(address_file):
        return None

    with open(address_file, "r") as f:
        address = f.read().strip()

    return address if address else None


def get_contract(contract_address=None):
    """
    Returns the Web3 Contract instance.
    Automatically loads the deployed contract address from contract_address.txt if not provided.
    Returns None if Web3 is not connected or the address is invalid.
    """
    web3_instance = get_web3()
    if not web3_instance:
        return None

    # Auto-load address from file if not explicitly passed
    if not contract_address:
        contract_address = get_deployed_contract_address()

    if not contract_address:
        return None

    # Validate checksum address
    if not web3_instance.is_address(contract_address):
        return None

    contract_address = web3_instance.to_checksum_address(contract_address)

    # Load ABI
    base_dir = os.path.dirname(os.path.abspath(__file__))
    abi_path = os.path.join(base_dir, "contract_abi.json")

    with open(abi_path, "r") as f:
        abi = json.load(f)

    return web3_instance.eth.contract(address=contract_address, abi=abi)
